### ISSUE TITLE
Running this on Mac

### ISSUE THREAD

**Issue by mattgaidica** [dimi2/DyAnnotationExtractor#1]
I'm trying to execute the jar file with the following errors:

Exception in thread "main" java.lang.NoClassDefFoundError: com/itextpdf/kernel/pdf/canvas/parser/listener/ITextExtractionStrategy
	at dsk.anotex.importer.ImporterFactory.createImporter(ImporterFactory.java:24)
	at dsk.anotex.AnnotationExtractor.readAnnotations(AnnotationExtractor.java:74)
	at dsk.anotex.AnnotationExtractor.extractAnnotations(AnnotationExtractor.java:41)
	at dsk.anotex.ConsoleRunner.doExtract(ConsoleRunner.java:25)
	at dsk.anotex.ConsoleRunner.main(ConsoleRunner.java:91)
Caused by: java.lang.ClassNotFoundException: com.itextpdf.kernel.pdf.canvas.parser.listener.ITextExtractionStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I also tried building with gradle. I apologize, I'm new to running java scripts, do you have any suggestions? As I understood, iText was compiled within the jar, is that not true?

**Comment by dimi2** [comment]
Hello.

The iText library lives in separate JAR file. This error occurs when that file is not found in the classpath.

The easiest method to run DyAnnotationExtractor is to download the [distribution](https://github.com/dimi2/DyAnnotationExtractor/releases/download/1.0.3/DyAnnotationExtractor-1.0.3-dist.zip), extract it to some directory and run the script **'DyAnnotationExctractor.sh'** with appropriate parameters. The distribution contains the necessary JAR files in its 'library' sub-directory.

If this does not help, please post the start command line here (and the file names in the directory where it is executed). There could be something specific for Mac computers.

Greetings.
